import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import ToggleThemeProvider from "@/providers/ToggleThemeProvider";
import Footer from "@/components/shared/Footer";



const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ToggleThemeProvider>
          <NavBar />
          <main>{children}</main>
          <Footer/>
        </ToggleThemeProvider>
      </body>
    </html>
  );
}
